server/apps/cart/urls.py
from django.conf.urls import url, patterns
from django.views.generic import TemplateView

urlpatterns = patterns('',
                       url(r'cart/$', TemplateView.as_view(template_name="cart/checkout.html"), name='cart'),
)

server/apps/profile/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.details, name='details'),
    url(r'^orders/$', views.orders, name='orders'),
    url(r'^orders/(?P<pk>[0-9]+)/$', views.OrderDetailView.as_view(), name='order-detail'),
    url(r'^address/(?P<pk>\d+)/edit/$', views.address_edit,
        name='address-edit'),
    url(r'^favorites/$', views.UserFavoritesListView.as_view(), name='favorites'),
]

server/erp_cms/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

#from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()


urlpatterns = [
    # url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
    #     {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^profile/', include('apps.profile.urls', namespace='profile')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^select2/', include('django_select2.urls')),
    #url(r'^products/', include('apps.products.urls', namespace='product')),
    url(r'^checkout/', include('apps.cart.urls', namespace='checkout')),
    url(r'^theme/', include('apps.custom_theme.urls', namespace='theme')),

    url(r'^favit/', include('apps.favorite.urls', namespace='favit')),
    url(r'^calification/', include('apps.rating.urls', namespace="rating")),
    url(r'^theme-config/', include('apps.custom_theme.urls', namespace="custom_theme")),
    url(r'^api/v1/', include('erp_cms.urls_api', namespace='api')),
    url(r'^api/public/v1/', include('erp_cms.urls_public_api', namespace='api-public')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('djangocms_forms.urls')),
    url(r'^', include('cms.urls')),
]

# urlpatterns += i18n_patterns('',
#     url(r'^admin/', include(admin.site.urls)),  # NOQA
#     url(r'^', include('cms.urls')),
# )

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

server/erp_cms/templates/_breadcrumb.html
{% for ance in ancestors %}
    <li {% if ance.get_absolute_url == request.path %}class="active"{% endif %}>
        {% if not forloop.last %}
            <a href="{{ ance.get_absolute_url }}">{{ ance.get_menu_title }}</a>
        {% else %}
            {% if ance.get_absolute_url == request.path %}
                {{ ance.get_menu_title }}
            {% else %}
                <a href="{{ ance.get_absolute_url }}">{{ ance.get_menu_title }}</a>
            {% endif %}
        {% endif %}
    </li>
{% endfor %}

server/erp_cms/templates/_menu.html
{% load i18n menu_tags cache %}

{% for child in children %}
    <li class="{% if child.ancestor %}ancestor{% endif %}
        {% if child.selected %} active{% endif %}
        {% if child.children %} dropdown{% endif %}">
        {% if child.children %}
            <a class="dropdown-toggle" data-toggle="dropdown" href="{{ child.get_absolute_url }}">
                {{ child.get_menu_title }} <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                {% show_menu from_level to_level extra_inactive extra_active template "" "" child %}
            </ul>
        {% else %}
            <a href="{{ child.get_absolute_url }}"><span>{{ child.get_menu_title }}</span></a>
        {% endif %}
    </li>
    {% if class and forloop.last and not forloop.parentloop %}{% endif %}
{% endfor %}

server/erp_cms/templates/_messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-message{% if message.tags %} alert-{{ message.tags }}{% endif %}">
            <p>{{ message }}</p>
        </div>
    {% endfor %}
{% endif %}

server/erp_cms/templates/_top_bar.html
{% load menu_tags i18n products_app %}
{% get_product_app_url 'search' as url_search %}
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><img src="{{ custom_site.logo }}" alt="{{ custom_site.name }}"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% show_menu 0 1 100 100 "_menu.html" %}
            </ul>
            <form class="navbar-form navbar-left" method="get" action="{{ url_search }}">
                <div class="form-group">
                    <input type="text" name="search" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Buscar</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'checkout:cart' %}" title="My Cart">{% trans "My cart" %}</a></li>
                <li class="dropdown cart">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="badge" id="cart-quantity-items">0</span> Carro <span class="caret"></span></a>
                    <ul class="dropdown-menu" id="dropdown-cart-product-list">
                        <!-- CART -->
                    </ul>
                </li>
                {% if request.user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user }} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'profile:details' %}">Perfil</a></li>
                        <li><a href="{% url 'profile:orders' %}">Mis ordenes</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url "account_logout" %}">Salir</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{% url "account_login" %}">Entrar</a></li>
                <li><a href="{% url 'account_signup' %}">Registrarse</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

server/erp_cms/templates/analytics.html
{# INFO: from html5 boilerplate https://github.com/h5bp/html5-boilerplate/blob/master/index.html #}
{% if GOOGLE_ANALYTICS_ID %}
    <script>
    (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
    function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
    e=o.createElement(i);r=o.getElementsByTagName(i)[0];
    e.src='//www.google-analytics.com/analytics.js';
    r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
    ga('create','{{ GOOGLE_ANALYTICS_ID }}','auto');ga('send','pageview');
    </script>
{% endif %}

server/erp_cms/templates/base.html
<!DOCTYPE html>{% load i18n cms_tags sekizai_tags menu_tags %}
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>
        {% block title %}
        {% page_attribute page_title %} - {{ request.site.name }}
        {% endblock title %}
    </title>

    {% block meta %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <meta name="author" content="{% trans "Context Software" %}">

    {% endblock meta %}

    <!-- Bootstrap core CSS -->
    <link href="/static/default/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/static/default/lib/bootstrap/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/default/css/custom.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="/static/bower_components/toastr/toastr.min.css" />

    <link rel="stylesheet" href="/static/bower_components/owl-carousel/owl.carousel.css">
    <link rel="stylesheet" href="/static/bower_components/owl-carousel/owl.transitions.css">
    <link rel="stylesheet" href="/static/bower_components/owl-carousel/owl.theme.css">

    {% block stylesheet %}
    {% endblock stylesheet %}

    {% render_block "css" %}

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="/static/default/lib/bootstrap/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/static/default/lib/bootstrap/assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
</head>

<body {% block angular_app_declare_block %}{% endblock %} itemscope itemtype="http://schema.org/WebPage">
{% cms_toolbar %}

{% include '_top_bar.html' %}

{% block feature %}
    <div class="spacer spacer-md"></div>
{% endblock feature %}

<div class="container">
    {% block outerbreadcrumb %}

    {% if not request.path == '/' %}
    <div id="breadcrumb-container">
            <ol class="breadcrumb">
                {% block breadcrumb %}
                    {% show_breadcrumb  '_breadcrumb.html' %}
                {% endblock breadcrumb %}
            </ol>
    </div>
    {% endif %}
    {% endblock outerbreadcrumb %}

    {% block messages %}
    {% include "_messages.html" %}
    {% endblock messages %}

    {% block content %}
    {% placeholder "content" %}
    {% endblock %}
</div> <!-- /container -->

<footer class="footer">
    {% static_placeholder "Footer" %}
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<script src="/static/default/lib/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="/static/default/lib/bootstrap/assets/js/ie10-viewport-bug-workaround.js"></script>

<script src="/static/bower_components/owl-carousel/owl.carousel.min.js"></script>
{% render_block "js" %}
{% block footer_scripts %}
{% endblock footer_scripts %}

<script>
    var cart_url = "{% url "checkout:cart" %}";
</script>

<script type="text/javascript" src="/static/favit/js/favorite.js"></script>
<script type="text/javascript" src="/static/default/js/display_cart.js"></script>
<script type="text/javascript" src="/static/bower_components/toastr/toastr.js"></script>


<script>
    $(document).ready(function() {
        // TODO: This script lookup all carousel and add event on button previous and next
        if($('.owl-carousel').length > 0){
            $('.owl-carousel').each(function() {
                var $this = $(this),
                        owlCarousel = $this.data('owlCarousel'),
                        owlBtns = $this.data('navigationBtns'),
                        prevBtn, nextBtn;

                if (typeof owlCarousel === 'undefined' || typeof owlBtns === 'undefined') {
                    return;
                }

                for(var key in owlBtns) {
                    if (owlBtns[key].indexOf('next') == -1) {
                        prevBtn = $(owlBtns[key]);
                    }else {
                        nextBtn = $(owlBtns[key]);
                    }
                }
                prevBtn.on('click touchstart', function(e) {
                    owlCarousel.prev();
                    e.preventDefault();
                });
                nextBtn.on('click touchstart', function(e) {
                    owlCarousel.next();
                    e.preventDefault();
                });
            });
        }
    });

    toastr.options = {
        "closeButton": true,
        "debug": false,
        "newestOnTop": false,
        "progressBar": true,
        "positionClass": "toast-bottom-left",
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "5000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    };

</script>


</body>
</html>

server/erp_cms/templates/modal_close.html
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
<h1 style="text-align: center; padding-top: 40px;">{% trans 'Success change!' %}</h1>
<script>

    function reload(){
        var parent = (window.parent) ? window.parent : window;
        parent.location.reload();
    }

    reload();
</script>
</body>
</html>