server/apps/favorite/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('apps.favorite.views',
    url(r'^add-or-remove$', 'add_or_remove', name='add-or-remove'),
    url(r'^remove$', 'remove', name='remove'),
)

server/apps/profile/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.details, name='details'),
    url(r'^orders/$', views.orders, name='orders'),
    url(r'^orders/(?P<pk>[0-9]+)/$', views.OrderDetailView.as_view(), name='order-detail'),
    url(r'^address/(?P<pk>\d+)/edit/$', views.address_edit,
        name='address-edit'),
    url(r'^favorites/$', views.UserFavoritesListView.as_view(), name='favorites'),
]

server/erp_cms/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

#from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()


urlpatterns = [
    # url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
    #     {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^profile/', include('apps.profile.urls', namespace='profile')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^select2/', include('django_select2.urls')),
    #url(r'^products/', include('apps.products.urls', namespace='product')),
    url(r'^checkout/', include('apps.cart.urls', namespace='checkout')),
    url(r'^theme/', include('apps.custom_theme.urls', namespace='theme')),

    url(r'^favit/', include('apps.favorite.urls', namespace='favit')),
    url(r'^calification/', include('apps.rating.urls', namespace="rating")),
    url(r'^theme-config/', include('apps.custom_theme.urls', namespace="custom_theme")),
    url(r'^api/v1/', include('erp_cms.urls_api', namespace='api')),
    url(r'^api/public/v1/', include('erp_cms.urls_public_api', namespace='api-public')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('djangocms_forms.urls')),
    url(r'^', include('cms.urls')),
]

# urlpatterns += i18n_patterns('',
#     url(r'^admin/', include(admin.site.urls)),  # NOQA
#     url(r'^', include('cms.urls')),
# )

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

server/apps/favorite/models.py
# -*- coding: utf-8 -*-
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from .managers import FavoriteManager


class Favorite(models.Model):

    user = models.ForeignKey(getattr(settings, 'AUTH_USER_MODEL', 'auth.User'))
    target_content_type = models.ForeignKey(ContentType)
    target_object_id = models.PositiveIntegerField()
    target = generic.GenericForeignKey('target_content_type', 'target_object_id')
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)

    objects = FavoriteManager()

    class Meta:
        ordering = ["-timestamp"]
        get_latest_by = "timestamp"
        unique_together = ("user", "target_content_type", "target_object_id")
        verbose_name = _("favorite")
        verbose_name_plural = _("favorites")

    def __str__(self):
        return "{} favorited {}".format(self.user, self.target)

server/erp_apps/order/models.py
from datetime import datetime

from django.core.urlresolvers import reverse
from django.db import models
from django.db import transaction
from django.db.models import Sum
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _

from erp_apps.account_balance.models import Ticket
from erp_apps.client.models import Client
from erp_apps.core.models import BaseModel
from erp_apps.delivery.models import Delivery
from .exceptions import OrderItemException

ORDER_STATUS_OPTIONS = (
    (0, _('Canceled')),
    (1, _('Pending')),
    (2, _('Completed')),
    (3, _('Issued')),
)

ORDER_LAST_STATUS_OPTIONS = (
    (0, _('Canceled')),
    (1, _('Pending')),
    (2, _('Completed')),
    (3, _('Issued')),
    (4, _('Created'))
)


class Order(BaseModel):
    client = models.ForeignKey(Client, related_name='orders')
    status = models.IntegerField(choices=ORDER_STATUS_OPTIONS, default=1)
    datetime_last_status_change = models.DateTimeField(null=True, blank=True)
    # Transaction Saved Fields
    total = models.DecimalField(decimal_places=2, max_digits=12, editable=False, default=0)
    ticket = models.OneToOneField(Ticket, null=True)
    last_status_change = models.IntegerField(choices=ORDER_LAST_STATUS_OPTIONS, default=4)

    delivered = models.BooleanField(default=False)
    payed = models.BooleanField(default=False)

    def __init__(self, *args, **kwargs):
        super(Order, self).__init__(*args, **kwargs)
        try:
            self._status = self.objects.get(pk=self.pk).status if self.pk else 1
        except (models.ObjectDoesNotExist, AttributeError):
            self._status = 1

    def change_status(self):
        with transaction.atomic():
            self.datetime_last_status_change =  datetime.now()
            self.last_status_change = self._status
            self._status = self.status
            if self.status == 0: # Canceled order
                #self.save() # TODO: Esto va?
                for d_group in self.delivery_groups.filter(status=1):
                    d_group.status = 0
                    d_group.save()
                for payment in self.payments.filter(status=1):
                    payment.status = 0
                    payment.save()
            elif self.status == 2: # Completed Order
                for d_group in self.delivery_groups.all():
                    d_group.status = 2
                    d_group.save()

            self.save()

    def check_delivered(self):
        for item in self.items.all():
            quantity = Delivery.objects.filter(item=item, group__status=2, group__order=self)\
                .aggregate(Sum('quantity')).get('quantity__sum', 0)
            quantity_item_delivered = quantity if quantity else 0
            if item.quantity > quantity_item_delivered:
                self.delivered = False
                self.save()
                return False

        self.delivered = True
        self.save()

    def is_fully_paid(self):
        return self.payed

    def check_payed(self):
        total_payments_amount = self.payments.filter(status=2).aggregate(Sum('amount')).get('amount__sum', 0)
        self.payed = True if total_payments_amount and self.total <= total_payments_amount else False
        self.save()

    def __str__(self):
        return "#%s , $%s (%s)" %(self.id, self.total, self.get_status_display())

    def get_absolute_url(self):
        return reverse('profile:order-detail', kwargs={'pk': self.pk})

    def add_item(self, product, quantity, action='increment', *args, **kwargs):
        if product.available_stock_quantity >= quantity:
            if self.items.filter(product=product).exists():
                item = self.items.filter(product=product).first()
                item.quantity += quantity
            else:
                item = OrderItem(order=self, product=product, quantity=quantity, price=product.get_price_per_item())
            item.save()
            return item
        else:
            raise OrderItemException(message="El producto %s no tiene stock suficiente. El stock disponible es de %s"
                                             % (product, product.available_stock_quantity))

    def save(self, *args, **kwargs):
        if self._status != self.status:
            self.change_status()
        else:
            super(Order, self).save(*args, **kwargs)


class OrderItem(BaseModel):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.PROTECT)
    product = models.ForeignKey('product.ProductVariant', on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField()

    # Transaction Saved Fields
    product_name = models.CharField(max_length=20, editable=False)
    price = models.DecimalField(decimal_places=2, max_digits=12, editable=False)

    def __str__(self):
        return "(Order#%s) %s : %s" % (self.order.pk, self.product_name, self.quantity)

    def get_total(self):
        return float(self.quantity) * float(self.price)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.product_name = self.product.name
            self.price = self.product.price

        return super(OrderItem, self).save(*args, **kwargs)


@receiver(post_save, sender=OrderItem)
def order_item_post_save(sender, *args, **kwargs):
    """
        When create product variant then create stock
    """
    total_amount = 0
    order = kwargs['instance'].order
    for item in order.items.all():
        total_amount += item.quantity * item.price

    order.total = total_amount
    order.save()

server/apps/favorite/views.py
from django.http import HttpResponseNotAllowed, HttpResponseBadRequest, JsonResponse
from django.contrib.auth.decorators import login_required

from .models import Favorite


@login_required
def add_or_remove(request):

    if not request.is_ajax():
        return HttpResponseNotAllowed()

    user = request.user

    try:
        app_model = request.POST["target_model"]
        obj_id = int(request.POST["target_object_id"])
    except (KeyError, ValueError):
        return HttpResponseBadRequest()

    fav = Favorite.objects.get_favorite(user, obj_id, model=app_model)

    if fav is None:
        Favorite.objects.create(user, obj_id, app_model)
        status = 'added'
    else:
        fav.delete()
        status = 'deleted'

    response = {
        'status': status,
        'fav_count': Favorite.objects.for_object(obj_id, app_model).count()
    }

    return JsonResponse(response)


@login_required
def remove(request):

    if not request.is_ajax():
        return HttpResponseNotAllowed()

    user = request.user

    try:
        app_model = request.POST["target_model"]
        obj_id = int(request.POST["target_object_id"])
    except (KeyError, ValueError):
        return HttpResponseBadRequest()

    Favorite.objects.get_favorite(user, obj_id, model=app_model).delete()
    status = 'deleted'

    response = {
        'status': status,
    }

    return JsonResponse(response)

templates/venedor/userprofile/_sidebar.html
{% load i18n %}
<div class="widget">
    <h3>Menu</h3>

    <div class="list-group list-group-brand list-group-accordion">
        <a href="{% url 'profile:details' %}" class="list-group-item">{% trans 'My profile' %}
            <span class="sidebar-icon fa fa-user"></span>
        </a>
        <a href="{% url 'profile:orders' %}" class="list-group-item">{% trans 'My orders' %}
            <span class="sidebar-icon fa fa-list-alt"></span>
        </a>
        <a href="{% url 'profile:favorites' %}" class="list-group-item">{% trans 'My favorites' %}
            <span class="sidebar-icon fa fa-heart"></span>
        </a>
    </div><!-- End .list-group -->
</div>

<style>
    .sidebar h3{
        color: #676a70;
        text-transform: uppercase;
        font: 700 16px/46px "PT Sans", Arial, sans-serif;
        margin-bottom: 20px;
        background: #e1e4e5;
        padding-left: 30px;
    }

    .sidebar-icon{
        display: block;
        width: 25px;
        height: 25px;
        float: left;
    }
</style>

templates/venedor/userprofile/address-delete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Delete address" %} — {{ block.super }}{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li><a href="{% url 'profile:details' %}">{% trans "Your profile" %}</a></li>
    <li><a href=".">{% trans "Delete address" %}</a></li>
{% endblock breadcrumb %}

{% block content %}
    <h2>{% trans "Are you sure you want to delete the following address?" %}</h2>

    <div class="row">
        <div class="col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ address }}
                </div>
                <div class="panel-body">
                    <address>{% include "userprofile/snippets/address-details.html" with address=address %}</address>
                </div>
            </div>
        </div>
    </div>

    <form action="." method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
        <a href="{% url 'profile:details' %}" class="btn btn-link">{% trans "Cancel" %}</a>
    </form>
{% endblock content %}

templates/venedor/userprofile/address-edit.html
{% extends "userprofile/base.html" %}

{% load i18n bootstrap3 %}

{% block title %}{% trans "Edit Address" %} — {{ block.super }}{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li><span class="active">{% trans 'Edit address' %}</span><li>
{% endblock breadcrumb %}

{% block inner_content %}
    <div class="panel panel-default">
        <div class="panel-body">
            <form action="." method="post">
                {% csrf_token %}
                <fieldset>
                    <legend>{% trans "Address" %}</legend>
                    {% bootstrap_form address_form %}
                </fieldset>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="{% url 'profile:details' %}" class="btn btn-link">Cancel</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/venedor/userprofile/base.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Profile" %} — {{ block.super }}{% endblock %}


{% block content %}
    <div class="col-md-3 col-sm-4 col-xs-12 sidebar">
        {% include 'userprofile/_sidebar.html' %}
    </div>

    <div class="col-md-9 col-sm-8 col-xs-12">
        {% block inner_content %}
            {% endblock inner_content %}
    </div>

{% endblock %}

templates/venedor/userprofile/details.html
{% extends "userprofile/base.html" %}
{% load i18n %}

{% block title %}{% trans "Your profile" %} — {{ block.super }}{% endblock %}


{% block breadcrumb %}
    {{ block.super }}
    <li><span class="active">{% trans "Your profile" %}</span></li>
{% endblock breadcrumb %}

{% block inner_content %}
    <h2>{% trans "Profile" %}</h2>
    <p>
        <a href="{% url 'account_change_password' %}" class="btn btn-default">{% trans 'Change your password' %}</a>
        <a href="{% url 'account_email' %}" class="btn btn-default">{% trans 'Change your email address' %}</a>
    </p>


    <h3>{% trans "Your address" %}</h3>
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="col-sm-2">{% trans "Short alias" %}</th>
                <th class="col-sm-4">{% trans "Addressee" %}</th>
                <th class="col-sm-2"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th class="col-sm-2">
                    {{ address.street }}
                </th>
                <td class="col-sm-4">
                    {{ address.street }}
                </td>
                <td class="col-sm-2">
                    <a href="{% url 'profile:address-edit' pk=address.pk %}" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-edit"></i> {% trans "Edit" %}</a>
                </td>
            </tr>
        </tbody>
    </table>

    <div>
{#        <a href="{% url 'profile:address-create' %}" class="btn btn-default"><i class="glyphicon glyphicon-plus-sign"></i> {% trans "Add new address" %}</a>#}
    </div>


{% endblock %}

templates/venedor/userprofile/favorites.html
{% extends "userprofile/base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load favit_tags %}
{% block title %}{% trans "Your favorites" %} — {{ block.super }}{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li><span class="active">{% trans "Your favorites" %}</span></li>
{% endblock breadcrumb %}

{% block inner_content %}
        <header class="content-title">
            <h1 class="title">{% trans 'Your favorites' %}</h1>
            <p class="title-desc">Your products favorites. Add favorites products and know when new offert to interested product.</p>
        </header>

        <table class="table">
            <thead>
            <tr>
                <th class="table-title">{% trans 'Product' %}</th>
                <th class="table-title">{% trans "Actions" %}</th>
            </tr>
            </thead>
            <tbody>
            {% if products %}
                {% for product in products %}
                    <tr>
                        <td class="col-md-11" style="text-align: left;">
                            <div class="col-md-2">
                                {% if product.images.first %}
                                    <img class="img-thumbnail" style="min-width: 100px; min-height: 100px; width: 100px;" src="{{ product.images.first.image.url }}" alt="{{ product.name }}" draggable="false">
                                {% else %}
                                    <img class="img-thumbnail" style="min-width: 100px; min-height: 100px; width: 100px;" src="{% static 'images/product-image-placeholder.png' %}" alt="" >
                                {% endif %}
                            </div>
                            <div class="col-md-10">
                                <h5><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h5>
                                <p>{{ product.description|safe }}</p>

                            </div>
                        </td>
                        <td class="col-md-1" style="vertical-align: middle; text-align: center;">
                            {% unfave_button product %}
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <p>{% trans 'You dont have favorites.' %}</p>
            {% endif %}

            </tbody>
        </table>

{% endblock %}

templates/venedor/userprofile/order_detail.html
{% extends "userprofile/base.html" %}
{% load i18n thumbnail %}

{% block title %}{% trans "Order" %} {{ order }} — {{ block.super }}{% endblock %}

{% block breadcrumb %}
{{ block.super }}
<li><a href="{% url 'profile:orders' %}">{% trans "Your orders" %}</a></li>
<li><span class="active"></span>{{ order }}</li>
{% endblock breadcrumb %}

{% block inner_content %}
<header class="content-title">
    <h1 class="title">{% trans 'Order Detail' %}</h1>
    <p class="title-desc"></p>
</header>
<div class="row">
    <div class="col-sm-12">
        <p class="text-muted">Número de orden: # {{ order.id }} </p>
        <p class="text-muted">Estado: {{ order.get_status_display }} </p>
    </div>
</div>

<div class="panel panel-default table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th class="col-md-6">{% trans "Name" %}</th>
            <th class="col-md-2">{% trans "Quantity" %}</th>
            <th class="col-md-2 text-right">{% trans "Price" %}</th>
            <th class="col-md-2 text-right">{% trans "Subtotal" %}</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th colspan="3">{% trans "Total" %}</th>
            <th class="text-right">{{ order.total }}</th>
        </tr>
        </tfoot>
        <tbody>

        {% for item in order.items.all %}
        <tr >
            <td><img src="{{ item.product.product.images.first.image|thumbnail_url:'150' }}" class="img-responsive img-thumbnail img-table pull-left">{{ item.product }}</td>
            <td class="text-center">{{ item.quantity }}</td>
            <td class="text-right">$ {{ item.price }} </td>
            <td class="text-right">$ {{ item.get_total | floatformat:2}}</td>
        </tr>
        {% endfor %}

        </tbody>
    </table>
</div>
{% if not order.is_fully_paid %}
<div class="spacer spacer-sm"></div>
<button class="pull-right btn btn-custom">Pagar</button>
{% endif %}

{% endblock inner_content %}

templates/venedor/userprofile/orders.html
{% extends "userprofile/base.html" %}
{% load i18n %}

{% block title %}{% trans "Your orders" %} — {{ block.super }}{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li><span class="active">{% trans "Your orders" %}</span></li>
{% endblock breadcrumb %}

{% block inner_content %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="col-sm-2">
                    {% trans "Order #" %}
                </th>
                <th class="col-sm-2">
                    {% trans "Date" %}
                </th>
                <th class="col-sm-2">
                    {% trans "Price" %}
                </th>
                <th class="col-sm-2">
                    {% trans "Status" %}
                </th>
                <th class="col-sm-2">
                    {% trans "Last status change" %}
                </th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
                <tr>
                    <td class="col-sm-2">
                        <a href="{% url 'order:detail' order.pk %}">{{ order.pk }}</a>
                    </td>
                    <td class="col-sm-2">
                        {{ order.created_at }}
                    </td>
                    <td class="col-sm-2">
                        $ {{ order.total }}
                    </td>
                    <td class="col-sm-2">
                        <span class="label label-default">{{ order.get_status_display }}</span>
                    </td>
                    <td class="col-sm-2">
                        <span class="label label-default">{{ order.get_last_status_change_display }}</span>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if not orders %}
        <p>No tienes ninguna orden registrada</p>
    {% endif %}
{% endblock %}